services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_USER=lms
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lms
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql-data:
