INSERT INTO users (name, email, password, role)
VALUES ('Ali Rezaei', 'ali.rezaei@example.com', 'password123', 'Admin'),
       ('Sara Ahmadi', 'sara.ahmadi@example.com', 'password123', 'Student'),
       ('Mohammad Karimi', 'm.karimi@example.com', 'password123', 'Instructor'),
       ('Fatemeh Sadeghi', 'f.sadeghi@example.com', 'password123', 'Student'),
       ('Reza Jalali', 'reza.jalali@example.com', 'password123', 'Student'),
       ('Nasim Moradi', 'nasim.moradi@example.com', 'password123', 'Instructor'),
       ('Hamed Ghasemi', 'hamed.gh@example.com', 'password123', 'Student'),
       ('Laleh Norouzi', 'l.norouzi@example.com', 'password123', 'Student'),
       ('Amir Hosseini', 'amir.hosseini@example.com', 'password123', 'Admin'),
       ('Shirin Jafari', 'shirin.jafari@example.com', 'password123', 'Student'),
       ('Nima Salari', 'nima.salari@example.com', 'password123', 'Student'),
       ('Zahra Bahrami', 'zahra.bahrami@example.com', 'password123', 'Student'),
       ('Hossein Nikfar', 'hossein.nikfar@example.com', 'password123', 'Instructor'),
       ('Mona Aslani', 'mona.aslani@example.com', 'password123', 'Student'),
       ('Kaveh Mohammadi', 'kaveh.m@example.com', 'password123', 'Student'),
       ('Tara Abbasi', 'tara.abbasi@example.com', 'password123', 'Admin'),
       ('Ehsan Samiei', 'ehsan.samiei@example.com', 'password123', 'Instructor'),
       ('Roya Mansouri', 'roya.m@example.com', 'password123', 'Student'),
       ('Sina Rajabi', 'sina.rajabi@example.com', 'password123', 'Student'),
       ('Parisa Zand', 'parisa.zand@example.com', 'password123', 'Student');
